# Generated by Django 4.0.4 on 2022-06-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Florence', '0002_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='product_name',
            new_name='category_name',
        ),
    ]
