# Generated by Django 4.0.4 on 2022-06-19 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Florence', '0007_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
    ]
