# Generated by Django 4.0.4 on 2022-06-19 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Florence', '0008_rename_category_name_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
    ]
